### ISSUE TITLE
Find problem instance corresponding to some result.

### ISSUE THREAD

**Issue by jusschwitalla** [QUARK-framework/QUARK#100]
When doing some evalution of QUARK results I sometimes need to know the problem instance to which an entry of the results.json corresponds.
My application stores the problem as  "problem_<rep_count>.json" in the store directory provided by the benchmark manager. Unfortunately I do not see an easy way to reconstruct the store directory for some given entry from results.json.

An easy way to solve this problem would be to let the benchmark manager write 'idx_backlog' in the results file.

**Comment by philross** [comment]
Hi @jusschwitalla, we actually included the `idx_backlog` to the results.json in a recent commit: https://github.com/QUARK-framework/QUARK/commit/4648cb97f7b9e789f891f51f0bc948832cca2daa#diff-2b50445ed5b8bf2d71538fd231a3cdc7e1692c80ea7b6767465e786b3b0d45f5R141 

This is currently only available in the `dev` branch, but we will merge this to the main branch today/tomorrow.
Aside from this we will think about whether we can supply any additional information to the results.json to make the identification easier.

**Comment by jusschwitalla** [comment]
Hi @Marvmann, works fine for me - thank you!
