### ISSUE TITLE
bug in summarize: solverConfigCombo not well defined.

### ISSUE THREAD

**Issue by jusschwitalla** [QUARK-framework/QUARK#14]
summarize does not always recognize that two data sets contribute to the same curve although they should.
That happens because 'solverConfigCombo' is created from a dictionary without applying some sorting.  

I think
        df['solverConfigCombo'] = df.apply(
            lambda row: '/\n'.join(
                ['%s: %s' % (key, value) for (key, value) in sorted(row['solver_config'].items(), key=lambda x:x[0])]) +
                        "\ndevice:" + row['device'] + "\nmapping:" + '/\n'.join(
                ['%s: %s' % (key, value) for (key, value) in sorted(row['mapping_config'].items(), key=lambda x:x[0])]), axis=1)

should solve the issue for solverConfigCombo (note the 'sorted').

'applicationConfigCombo' probably has the same issue but I have not checked that.

With best regards, Jürgen

**Comment by philross** [comment]
Thank you @jusschwitalla , I opened PR #15, which implements your changes for both solverConfigCombo and applicationConfigCombo.
