### ISSUE TITLE
git_uncommitted_changes returned with string type hint, used where bool is expected

### ISSUE THREAD

**Issue by MartinMeilinger** [QUARK-framework/QUARK#58]
As we discussed in the last Open Call, here is the issue for the people that weren't there.

In `utils.get_git_revision(...)`, `git_uncommitted_changes` is assigned a `bool`, unless something goes wrong. In that case, it is assigned "unknown". As a result of this, the method is typed to return two strings (first `git_revision_number`, then `git_uncommitted_changes`). `git_uncommitted_changes` is (as far as I can tell) only used in saving a benchmark run.

However, under `BenchmarkManager.run_benchmark(...)`, it is used as a parameter of a new `BenchmarkRecord` object. The definition of the initializer of `BenchmarkRecord` expects a `bool`, not a `str`. Therefore, PyCharm gives me a 'wrong type' warning.

Should we change the type hint in `BenchmarkRecord` to a string or do something else?

Since we had some uncertainties about Python's dynamic typing, here's a short presentation of how it works. If a variable is assigned a `bool`, even if its type hint says `str`, is still is a `bool` and treated as such.
The type hints are exactly what they're called: type *hints*.

```
>>> def foo() -> str:
...     return True
...
>>> test = foo()
>>> type(test)
<class 'bool'>
>>> test
True
>>> test2: str = "test2"
>>> test2
'test2'
>>> type(test2)
<class 'str'>
>>> test2 = foo()
>>> test2
True
>>> type(test2)
<class 'bool'>
```

**Comment by philross** [comment]
Thanks @MartinMeilinger, will fix this in the linked PR.
