### ISSUE TITLE
regarding pylint R1728 consider-using-generator

### ISSUE THREAD

**Issue by MartinMeilinger** [QUARK-framework/QUARK#65]
(from #55)

> > `src/modules/applications/optimization/PVC/PVC.py`, method `validate(...)`:
> > Is there a reason why you do `# pylint: disable=R1728` [(consider-using-generator)](https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/consider-using-generator.html), instead of using the generator as apparently suggested by pylint?
> > And what is the reason to use `list(set(list([...])))` in the first place?
> > 
> > `# pylint: disable=R1728` is used again in `src/modules/solvers/GreedyClassicalPVC.py` and in `src/modules/solvers/ReverseGreedyClassicalPVC.py` (both times in the method `run(...)`). The same question applies here.
> 
> Regarding # pylint: disable=R1728: Yes it would be nicer to move these lines to generators.

In the last Open Call, Marvin told me that he'd like to discuss this further to make sure we don't screw anything up.
Mostly the point is about the `list(set(list([...])))`, which uses a generator to create a list (`[...]`), only to wrap it in an explicit `list(...)`, followed by a `set(...)` and yet another `list(...)`. The full line is:
```
visited_seams = list(set(list([seam[0][0] for seam in solution if seam is not None])))  # pylint: disable=R1728
```
As far as I can see, `seam` contains the values `((seam, node), config, tool)` (maybe we should document that better btw), meaning `seam[0][0]` gets the visited seam of the PVC process.
Following that line of code, only the length of `visited_seams` is used to determine whether all seams got visited.
So, the purpose of this line is to extract all unique visited seams to then count how many there are.

Since you can also get the length of a set, the following line is much shorter, but equivalent in result:
```
visited_seams = {seam[0][0] for seam in solution if seam is not None}
```
(`{...}` creates a set.)

Is there anything I overlooked? If not, I'll create the PR in the next days.

**Comment by Marvmann** [comment]
Hi Martin,
I think this makes sense. Please feel free to create the PR, I will check it out next week.
