### ISSUE TITLE
device_name in QUARK2

### ISSUE THREAD

**Issue by jusschwitalla** [QUARK-framework/QUARK#82]
The constructor of Device requires 'device_name' as  argument. The other components have no required constructor argument. This is so in QUARK2 still. This sometimes causes trouble because a Device must be handeled different than the other components.

I would like to have a consistent behaviour in QUARK2. Either to have a 'name' argument in Core so that every QUARK module has a name or to remove the device_name from Device.
I would prefer the first option - it seems natural to me that each component has a name. In this case the name should be the name given in the QUARK modules configuration.

**Comment by Marvmann** [comment]
Fixed with PR #84
