### ISSUE TITLE
Option to raise exception when benchmark run fails

### ISSUE THREAD

**Issue by philross** [QUARK-framework/QUARK#94]
Currently, we will catch any exception in the `run_benchmark` function. However for some cases it might be useful to have an option that these exceptions are re-raised.

**Comment by philross** [comment]
@jusschwitalla We now merged the feature in the dev branch. In case you want QUARK to fail in case a single benchmark run fails, run QUARK with: `python src/main.py --failfast`

**Comment by jusschwitalla** [comment]
Super – danke!

Von: Philipp ***@***.***>
Gesendet: Mittwoch, 29. November 2023 14:43
An: QUARK-framework/QUARK ***@***.***>
Cc: Juergen Schwitalla ***@***.***>; Mention ***@***.***>
Betreff: Re: [QUARK-framework/QUARK] Option to raise exception when benchmark run fails (Issue #94)

Caution: External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.


@jusschwitalla<https://github.com/jusschwitalla> We now merged the feature in the dev branch. In case you want QUARK to fail in case a single benchmark run fails, run QUARK with: python src/main.py --failfast
